version: '3'

services:
  app:
    container_name: django
    build: .
    volumes:
      - static_volume:/app/static
    links:
      - selenium-firefox
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - app

  selenium-firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  static_volume: